### ISSUE TITLE
provision_xous.sh fails with jtag_gpio.py segmentation fault

### ISSUE THREAD

**Issue by ian-kelling** [betrusted-io/betrusted-scripts#6]
This is running on a raspberry pi 3b with ubuntu 20.04 64 bit on it,
connected up to a precursor, which had it's initial update
over usb fail part way through, on it's screen it says:

Betrusted/Precursor Bootloader v0.2.i
DEVELOPER KEY DETECTED
Signature check failed. powering down.

Running the failing command under gdb with -c and -d:

```
(gdb) run ./jtag_gpio.py -c -d -f ../../precursors/soc_csr.bin --raw-binary --spi-mode -r
Starting program: /usr/bin/python3 ./jtag_gpio.py -c -d -f ../../precursors/soc_csr.bin --raw-binary --spi-mode -r
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
Programming .bin file to FPGA: ../../precursors/soc_csr.bin
Using JTAGSPI mode with variant 'xc7s50', to address 0x00000000, verify is on
DEBUG:root:start: [<JtagLeg.RS: 2>, '0', 'reset'] () / reset
DEBUG:root:tms reset
DEBUG:root:start: [<JtagLeg.IR: 1>, '001001', 'idcode'] (IDCODE) / idcode
DEBUG:root:result: 0x11
DEBUG:root:start: [<JtagLeg.DR: 0>, '00000000000000000000000000000000', ' '] () /  
DEBUG:root:result: 0x362f093
DEBUG:root:start: [<JtagLeg.RS: 2>, '0', 'reset'] () / reset
DEBUG:root:tms reset
DEBUG:root:start: [<JtagLeg.IR: 1>, '001011', 'jprogram'] (JPROGRAM) / jprogram
DEBUG:root:result: 0x11
DEBUG:root:start: [<JtagLeg.IR: 1>, '010100', 'isc_noop'] (ISC_NOOP) / isc_noop
DEBUG:root:result: 0x1
DEBUG:root:start: [<JtagLeg.DL: 3>, '0', 'initdelay'] () / initdelay
DEBUG:root:start: [<JtagLeg.IR: 1>, '010100', 'isc_noop'] (ISC_NOOP) / isc_noop
DEBUG:root:result: 0x11
DEBUG:root:start: [<JtagLeg.RS: 2>, '0', 'reset'] () / reset
DEBUG:root:tms reset
DEBUG:root:start: [<JtagLeg.IRD: 6>, '000101', 'cfg_in'] (CFG_IN) / cfg_in
DEBUG:root:result: 0x11
DEBUG:root:start: JtagLeg.DRC config data of length 2011392
DEBUG:root:leaving config
DEBUG:root:result: 0x0
DEBUG:root:start: [<JtagLeg.RS: 2>, '0', 'reset'] () / reset
DEBUG:root:tms reset
DEBUG:root:start: [<JtagLeg.IR: 1>, '001001', 'idcode'] (IDCODE) / idcode
DEBUG:root:result: 0x35
DEBUG:root:start: [<JtagLeg.DR: 0>, '00000000000000000000000000000000', ' '] () /  
DEBUG:root:result: 0x362f093
DEBUG:root:start: [<JtagLeg.IR: 1>, '000010', 'user1'] (USER1) / user1
DEBUG:root:result: 0x35

Program received signal SIGSEGV, Segmentation fault.
0x0000fffff77417d4 in jtag_prog_rbk (
    bitstream=0xfffff4bb7040 "1", '0' <repeats 27 times>, "1111110011111", '0' <repeats 24 times>, gpio=gpio@entry=4160671744, readback=0x1fbcd90 "") at gpio-ffi.c:97
97        GPIO_CLR = 1 << TMS_PIN; // TMS is known to be zero for this operation
(gdb) backtrace
#0  0x0000fffff77417d4 in jtag_prog_rbk (
    bitstream=0xfffff4bb7040 "1", '0' <repeats 27 times>, "1111110011111", '0' <repeats 24 times>, gpio=gpio@entry=4160671744, readback=0x1fbcd90 "") at gpio-ffi.c:97
#1  0x0000fffff774114c in _cffi_f_jtag_prog_rbk (self=<optimized out>, args=<optimized out>)
    at gpioffi.c:704
#2  0x0000000000594fa0 in PyCFunction_Call ()
#3  0x00000000005959e4 in _PyObject_MakeTpCall ()
#4  0x0000000000503020 in _PyEval_EvalFrameDefault ()
#5  0x00000000004fc9d4 in _PyEval_EvalCodeWithName ()
#6  0x00000000005954bc in _PyFunction_Vectorcall ()
#7  0x00000000004fe768 in _PyEval_EvalFrameDefault ()
#8  0x00000000004fc9d4 in _PyEval_EvalCodeWithName ()
#9  0x00000000005954bc in _PyFunction_Vectorcall ()
#10 0x00000000004ff5d0 in _PyEval_EvalFrameDefault ()
#11 0x00000000005952c8 in _PyFunction_Vectorcall ()
#12 0x00000000004fe640 in _PyEval_EvalFrameDefault ()
#13 0x00000000004fc9d4 in _PyEval_EvalCodeWithName ()
#14 0x0000000000662f90 in PyEval_EvalCode ()
#15 0x000000000064f040 in ?? ()
#16 0x000000000064f10c in ?? ()
#17 0x000000000064f204 in ?? ()
#18 0x000000000064f618 in PyRun_SimpleFileExFlags ()
#19 0x000000000069d7dc in Py_RunMain ()
#20 0x000000000069e004 in Py_BytesMain ()
#21 0x0000fffff7e79d50 in __libc_start_main (main=0x59b5d4 <_start+56>, argc=9, 
    argv=0xfffffffff788, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=<optimized out>) at ../csu/libc-start.c:308
#22 0x000000000059b5d0 in _start ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

```

I added faulthalder to get a python stack trace, and got this:

```
Current thread 0x0000ffff8eacf010 (most recent call first):
  File "./jtag_gpio.py", line 1293 in exchange
  File "./jtag_gpio.py", line 491 in do_spi_bitstream
  File "./jtag_gpio.py", line 1097 in main
  File "./jtag_gpio.py", line 1421 in <module>
```

**Comment by ian-kelling** [comment]
I realized I didn't have the hat pushed down far enough on the PI, which might have caused this, but then I broke my PI :(. I'll have to wait to get another one.

**Comment by ian-kelling** [comment]
I'll also note that your video says that pi 3 b+ is what testing is done on, but pretty much the only pi available from US retailers is the PI 4. On ebay PI 3 B+ is around $200. So, I suggest getting a PI 4 and testing your scripts on it.
